# DRIVER Y CONEXIÓN
db.driver=com.mysql.cj.jdbc.Driver
# SEGURIDAD Y CODIFICACION UTF-8 PARA ALINEARNOS CON EL UNICODE DE LA BBDD
db.url=jdbc:mysql://localhost:3306/hoteldb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8

# CREDENCIALES
db.username=root
db.password=123abc